### ISSUE TITLE
Native events with EventTarget

### ISSUE THREAD

**Issue by stackoverfloweth** [kitbagjs/events#13]
Have you considered just implementing native events with EventTarget? It's in Node ever since v14, and once is an option on addEventListener. TypeScript natively supports it as well.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget

Pulled from discussion on Reddit from [jessepence](https://www.reddit.com/user/jessepence/)

**Comment by pleek91** [comment]
No planning on using native events for this for now.
