### ISSUE TITLE
Ability to set BroadcastManager/update EmitterOptions

### ISSUE THREAD

**Issue by agrohs** [kitbagjs/events#16]
I'd like to add the ability to set/update the BroadcastManager after the emitter is initially created (and/or even to add a more generic `update` method that would allow updating the `EmitterOptions` on the emitter instance some time after the initial `createEmitter` has been called)

I'm happy to contribute a PR to add it in, but wanted to see if any concerns/isues/reasons why you may not want that in the core library before spending the time?

**Comment by pleek91** [comment]
@agrohs thanks for the issue! Are you just looking to update the broadcast channel (the only part of the `EmitterOptions` currently). Or are you looking to add new events to the emitter after it has been created? 

Having a way to update the options after its been created seems reasonable. Happy to review a PR for that 👍

**Comment by agrohs** [comment]
Awesome, I'll see if I can get something together next weekend or so @pleek91!

My main use case is just being able to set/change the BroadcastChannel after the emitter has already been instantiated, but I'm happy to build it to be a more generic new method in case at any point you guys wind up adding other `EmitterOptions` to the constructor

**Comment by pleek91** [comment]
@agrohs I love the idea of a more generic method that would update any settings. But idk what settings there might be in the future. 

Can you tell me more about your use case of changing the broadcast channel? Very curious. When I built this I imagined this as just a way to share the events across browsing contexts. So the channel didn't really matter as long as it was the same.

**Comment by agrohs** [comment]
It's just more of a scoped variable thing for our use case - in that the emitter is instantiated before we know what the broadcast channel is that is shared across all instances of our app. So the idea would be that we would instantiate the emitted and then in a react hook to set the broadcast channel as soon as it is known on initial load of the app.

**Comment by pleek91** [comment]
@agrohs I put up a PR for updating the settings post creation. I think that will solve your problem. I need to write some docs and then I'll get that released. 

I'm curious about how you're determining the name of the broadcast channel. Is that dynamic in some way or is it using an existing channel? I imagined the channel name isn't really important it just needs to be unique so it could be provided statically at creation. But I'm wondering if you have multiple apps or something that need to share a common emitter across contexts. 

I'd also love to hear any other feedback/requests you might have.

**Comment by agrohs** [comment]
I was literally just about to dig into this finally @pleek91 - but looks like you've got it exactly what I was thinking in that PR!

Our primary use case is that we do have multiple instances of our app - each on has a unique id that is determined at runtime. The idea is that we were thinking that we'd instantiate the emitter itself and then set the broadcastChannel on it on initial load as soon as we know the id.

And then the real scenario is that there are multiple "locations" of our app that share the same id/now the same broadcast channel that each live in a different iframe and we'd use this for any of them to communicate with each other.

I did a quick glance on that PR and think it will do exactly what we need.

**Comment by pleek91** [comment]
@agrohs sounds very cool. I hope this package is helping simplify things for you! I just published 0.1.0 to npm so you should be able to install latest and use that `setOptions` method to configure your broadcast channel 👍

**Comment by agrohs** [comment]
Amazing, thanks so much @pleek91!
